[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[build]
default-target = "aarch64-unknown-linux-gnu"

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
]
